use ez_ffmpeg::filter::frame_pipeline_builder::FramePipelineBuilder;
use ez_ffmpeg::subtitle::SubtitleFilter;
use ez_ffmpeg::{AVMediaType, FfmpegContext, Output};

/// Burns subtitles into a video natively (pure-Rust renderer inside the frame
/// pipeline) — no `--enable-libass` FFmpeg build flag, no system libass, and
/// no temp subtitle files needed.
fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Subtitles straight from memory (e.g. generated by ASR); .srt/.ass/.vtt
    // files work too via `.file("subs.srt")`, and full in-memory ASS scripts
    // with styling via `.ass_content(script)`.
    let srt = "\
1
00:00:00,500 --> 00:00:02,500
Hello from ez-ffmpeg!

2
00:00:02,500 --> 00:00:04,800
<i>Native pure-Rust burn-in</i> - no FFmpeg build flags needed.
";

    let filter = SubtitleFilter::builder()
        .srt_content(srt)
        // Style overrides use FFmpeg `force_style` semantics:
        .force_style("FontSize=28,Outline=1")
        // For reproducible fonts (e.g. app-shipped ones):
        // .fonts_dir("assets/fonts")
        // .default_font_file("assets/fonts/NotoSansSC-Regular.otf")
        // .font_provider(ez_ffmpeg::subtitle::FontProvider::None)
        .build()?;

    // Attach on the output side: subtitles render against the final,
    // post-filter-graph geometry, right before encoding.
    let pipeline: FramePipelineBuilder = AVMediaType::AVMEDIA_TYPE_VIDEO.into();
    FfmpegContext::builder()
        .input("../../test.mp4")
        .output(
            Output::from("output.mp4")
                .add_frame_pipeline(pipeline.filter("subtitles", Box::new(filter))),
        )
        .build()?
        .start()?
        .wait()?;

    println!("wrote output.mp4 with burned-in subtitles");
    Ok(())
}
