[package]
name = "async"
version = "0.1.0"
edition = "2024"
authors = ["Yeauty <YeautyYE@gmail.com>"]
publish = false

[dependencies]
ez-ffmpeg = { path = "../../../ez-ffmpeg" , features = ["async"]}
tokio = { version = "1", features = ["full"] }
