[package]
name = "rtmp_streaming"
version = "0.1.0"
edition = "2025"
authors = ["Yeauty <YeautyYE@gmail.com>"]
publish = false

[dependencies]
ez-ffmpeg = { path = "../../../ez-ffmpeg" , features = ["rtmp"]}
